# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . ./

# Ensure the entrypoint script is executable
RUN chmod +x bin.mjs

# Run the entrypoint
ENTRYPOINT ["node", "./bin.mjs"]
